bloodDonation/urls.py
from django.urls import path
from .views import doner_list,new_doner
app_name = 'bloodDonation'
urlpatterns = [
    path('', doner_list, name='list'),
    path('new/', new_doner, name='newDoner'),
]

bloodDoner/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('', include("bloodDonation.urls"),name='bloodDoner'),
    path('admin/', admin.site.urls),
    
]

bloodDonation/models.py
from django.db import models
from django import forms
# Create your models here.



class Donator(models.Model):

   
    name = models.CharField(max_length=30)
    sex = models.CharField(max_length=30)
    contact_number = models.CharField(max_length=20)
    age = models.IntegerField(null=True)
    blood_type= models.CharField(max_length=10)
    location= models.CharField(max_length=255,null=True)
    joined = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.name
class AddDoner(forms.ModelForm):
    class Meta:
        model=Donator
        fields=['name','sex','contact_number']

bloodDonation/forms.py
from django import forms
from . import models
class AddDoner(forms.ModelForm):

    class Meta():
        model=models.Donator
        fields=['name','location','contact_number','age']
    
    
    def clean_contact_number(self):
        num=self.cleaned_data['contact_number']
        if (num[:3]!='+88'):
            num='+88'+num
            return num
        return self.cleaned_data['contact_number']
        

bloodDonation/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import Donator
from django.db.models import Q
from . import forms
# Create your views here.
def doner_list(request):
    donors =Donator.objects.all()
    # print(donors)
    if(request.method == "POST"):
        search=request.POST["search"]
        category=request.POST["category"]
        if(category=="all"):
            donors = Donator.objects.filter(Q(name__icontains=search)|
            Q(name__icontains=search.capitalize())|
            Q(contact_number__icontains=search)|
            Q(age__icontains=search)|
            Q(sex__icontains=search)|
            Q(blood_type__icontains=search)|
            Q(location__icontains=search.capitalize())|
            Q(location__icontains=search))
        elif(category=="name"):
            donors = Donator.objects.filter(Q(name__icontains=search)|Q(name__icontains=search.capitalize()))
        elif(category=="bloodType"):
            donors = Donator.objects.filter(blood_type__icontains=search)
        elif(category=="age"):
            donors = Donator.objects.filter(age__icontains=search)
        elif(category=="number"):
            donors = Donator.objects.filter(contact_number__icontains=search)
        elif(category=="location"):
            donors = Donator.objects.filter(Q(location__icontains=search.capitalize())|Q(location__icontains=search))
        return render(request,'bloodDonation/list.html',{'doners':donors})
    return render(request,'bloodDonation/list.html',{'doners':donors})


def new_doner(request):
    form=forms.AddDoner()
    if(request.method=="POST"):
        form=forms.AddDoner(request.POST)
        if form.is_valid:
            temp=form.save(commit=False)
            temp.sex=request.POST['sex']
            temp.blood_type=request.POST['blood_type']
            temp.save()
            return redirect("bloodDonation:list")
    return render(request,'bloodDonation/newDoner.html',{'form':form})

bloodDonation/templates/bloodDonation/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Blood Donation</title>

      <!-- Compiled and minified CSS -->
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      <!-- Compiled and minified JavaScript -->
      <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

              
</head>
<body>
    
    <nav>
        <div class="container">
        <div class="nav-wrapper">
          <a href="#" class="brand-logo">Blood Donation</a>
          <ul id="nav-mobile" class="right hide-on-med-and-down">
            <li><a href=" {% url 'bloodDonation:list'  %} ">Donator List</a></li>
            <li><a href="{% url 'bloodDonation:newDoner' %}" class="waves-effect waves-light btn-large">Be A Donor</a></li>
          </ul>
        </div>
    </div>  
      </nav>
        <div class="container">
          <h2 class="center">List Of Donor</h2>
          <div class="row">
              <form action="#" method="POST">
                {% csrf_token %}
                <div class="input-field col s6">
                    <i class="material-icons prefix">search</i>
                    <input id="search" name="search" class="validate">
                  </div>
                  <div class="input-field col s3">
                    <select name="category">
                      <option value="all" selected>All</option>
                      <option value="name">Name</option>
                      <option value="bloodType">Blood Type</option>
                      <option value="age">Age</option>
                      <option value="location">Location</option>
                      <option value="number">Contact Number</option>
                    </select>
                    <label>Category Select </label>
                  </div>
                  <button class="col s3 waves-effect waves-light btn" style="margin-top: 20px" type="submit">Search</button>
                </form>
          </div>
          
          <table class="centered responsive-table highlight">
            <thead>
              <tr>
                  <th>Name</th>
                  <th>Sex</th>
                  <th>Contact Number</th>
                  <th>Blood Type</th>
                  <th>Age</th>
                  <th>Location</th>
              </tr>
            </thead>
    
            <tbody>
              {% for doner in doners %}
              <tr>
                <td>{{doner.name}}</td>
                <td>{{doner.sex}}</td>
                <td>{{doner.contact_number}}</td>
                <td>{{doner.blood_type}}</td>
                <td>{{doner.age}}</td>
                <td>{{doner.location}}</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
        <script>
         document.addEventListener('DOMContentLoaded', function() {
          var elems = document.querySelectorAll('select');
          var instances = M.FormSelect.init(elems);
        });

        </script>
</body>
</html>

bloodDonation/templates/bloodDonation/newDoner.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Blood Donation</title>

      <!-- Compiled and minified CSS -->
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      <!-- Compiled and minified JavaScript -->
      <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

              
</head>
<body>
    
    <nav>
        <div class="container">
        <div class="nav-wrapper">
          <a href="#" class="brand-logo">Blood Donation</a>
          <ul id="nav-mobile" class="right hide-on-med-and-down">
            <li><a href=" {% url 'bloodDonation:list'  %} ">Donator List</a></li>
            <li><a href="{% url 'bloodDonation:newDoner' %}" class="waves-effect waves-light btn-large">Be A Donor</a></li>
          </ul>
        </div>
    </div>  
      </nav>
        <div class="container">
          <h2 class="center">Join As Donor </h2>
          <form action="/new/" method="post">
            {% csrf_token %}  
            {{form}}
            <div class="row">
                    <div class="input-field col s6">
                            <select name="sex" required>
                              <option value="" selected>Please Select Gender</option>
                              <option value="Male">Male</option>
                              <option value="Female">Female</option>
                        </select>
                        <label>Gender Select </label>
                    </div>
                    <div class="input-field col s6">
                            <select name="blood_type" required>
                              <option value="" selected>Please Select Blood Group</option>
                              <option value="O+">O+</option>
                              <option value="O-">O-</option>
                              <option value="A+">A+</option>
                              <option value="A-">A-</option>
                              <option value="AB+">AB+</option>
                              <option value="AB-">AB-</option>
                              <option value="B+">B+</option>
                              <option value="B-">B-</option>
                        </select>
                        <label>Blood Group Select </label>
                    </div>
            </div>
            
            <button type="submit" class="waves-effect waves-light btn-large center-align" style="text-align: center">Join</button>
          </form>
          

        </div>
<script>
document.addEventListener('DOMContentLoaded', function() {
    var elems = document.querySelectorAll('select');
    var instances = M.FormSelect.init(elems);
});

</script> 
</body>
</html>